pipeline:
  name: storybook-test-daily
  identifier: storybooktestdaily
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: storybook
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Compile
                  identifier: Compile
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      yarn task --task compile --start-from=auto --no-link --debug
                      git diff --exit-code
                    envVariables:
                      NODE_OPTIONS: "--max_old_space_size=6144"
              - step:
                  type: Run
                  name: Publish to verdaccio
                  identifier: Publish_to_verdaccio
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      cd code
                      yarn local-registry --publish
                    envVariables:
                      NODE_OPTIONS: "--max_old_space_size=6144"
              - step:
                  type: Run
                  name: Provide error if curl is not present
                  identifier: Provide_error_if_curl_is_not_present
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      which curl > curl_exists; echo $? | grep -q '1' && echo curl not installed && rm curl_exists && exit 1
                      rm curl_exists
                    envVariables:
                      NODE_OPTIONS: "--max_old_space_size=6144"
              - step:
                  type: Run
                  name: Discord setting success condition
                  identifier: Discord_setting_success_condition
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      echo 'export DISCORD_BUILD_STATUS="success"'
                    envVariables:
                      NODE_OPTIONS: "--max_old_space_size=6144"
              - step:
                  type: Run
                  name: Provide if non bash shell
                  identifier: Provide_if_non_bash_shell
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      if [ ! -x /bin/bash ]; then
                        echo Bash not installed.
                        exit 1
                      fi

                      ls
                    envVariables:
                      NODE_OPTIONS: "--max_old_space_size=6144"
              - step:
                  type: SaveCacheGCS
                  name: Save Yarn Cache
                  identifier: Save_Yarn_Cache
                  spec:
                    connectorRef: gcpdhruba
                    bucket: test-storybook-yarn
                    key: prettydocs-yarn-2-cache-v4--{{ checksum "code/yarn.lock" }}--{{ checksum "scripts/yarn.lock" }}
                    sourcePaths:
                      - .yarn/berry/cache
                    archiveFormat: Tar
          sharedPaths:
            - /tmp/storybook/
    - parallel:
        - stage:
            name: create-sandboxes
            identifier: createsandboxes
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run_4
                      identifier: Run_4
                      spec:
                        shell: Sh
                        command: |-
                          cd code
                          yarn install
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          yarn task --task compile --start-from=auto --no-link --debug
                          git diff --exit-code
                  - step:
                      type: Run
                      name: Run_3
                      identifier: Run_3
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          cd code
                          yarn local-registry --publish
                  - step:
                      type: Run
                      name: Creating sandboxes
                      identifier: Creating_sandboxes
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          yarn task --task sandbox --template $(yarn get-template daily sandbox) --no-link --start-from=never --junit
                        envVariables:
                          NODE_OPTIONS: "--max_old_space_size=6144"
            when:
              pipelineStatus: All
        - stage:
            name: lint
            identifier: lint
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Sh
                        command: |-
                          cd code
                          yarn install
                  - step:
                      type: Run
                      name: Run_3
                      identifier: Run_3
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          yarn task --task compile --start-from=auto --no-link --debug
                          git diff --exit-code
                  - step:
                      type: Run
                      name: Run_4
                      identifier: Run_4
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          cd code
                          yarn local-registry --publish
                  - step:
                      type: Run
                      name: Run_1
                      identifier: Run_1
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          cd code
                          ls
                          yarn lint
            when:
              pipelineStatus: All
        - stage:
            name: unit-tests
            identifier: unittests
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Sh
                        command: |-
                          cd code
                          yarn install
                  - step:
                      type: Run
                      name: Run_3
                      identifier: Run_3
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          yarn task --task compile --start-from=auto --no-link --debug
                          git diff --exit-code
                  - step:
                      type: Run
                      name: Run_4
                      identifier: Run_4
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          cd code
                          yarn local-registry --publish
                  - step:
                      type: Run
                      name: Run_1
                      identifier: Run_1
                      spec:
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          cd code
                          yarn test --coverage --ci --maxWorkers=6
            when:
              pipelineStatus: All
    - stage:
        name: build-sandboxes
        identifier: buildsandboxes
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      yarn task --task build --template $(yarn get-template daily build) --no-link --start-from=never --junit
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |
                      #!/bin/bash -eo pipefail
                      yarn ts-node ./event-log-checker build $(yarn get-template daily build)
                  when:
                    stageStatus: All
                  failureStrategies: []
        strategy:
          parallelism: 31
        when:
          pipelineStatus: All
  allowStageExecutions: true
